version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: redis-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redis
#      MYSQL_USER: root
#      MYSQL_PASSWORD: my_user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
